// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC8rJLlfSK1ofVQvxRcnnC5vt2cLB_4YY',
    appId: '1:915439043742:web:e4e0451eaf5c4bfe7ea78f',
    messagingSenderId: '915439043742',
    projectId: 'kemia-projeto-integracao-esms',
    authDomain: 'kemia-projeto-integracao-esms.firebaseapp.com',
    storageBucket: 'kemia-projeto-integracao-esms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2v_cPbqS2Fw2r6ASKTl2hs6A3q4VPX2A',
    appId: '1:915439043742:android:16e9aeb3d457f3807ea78f',
    messagingSenderId: '915439043742',
    projectId: 'kemia-projeto-integracao-esms',
    storageBucket: 'kemia-projeto-integracao-esms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_yI75okXBxNRFee5U_YsToxe7nGtCHd8',
    appId: '1:915439043742:ios:dace1bfe2105be7d7ea78f',
    messagingSenderId: '915439043742',
    projectId: 'kemia-projeto-integracao-esms',
    storageBucket: 'kemia-projeto-integracao-esms.firebasestorage.app',
    iosBundleId: 'com.example.testeKemia',
  );
}
